version: "3.8"
services:
  db:
    image: postgres
    container_name: rss-aggregator-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: jgeschwa
      POSTGRES_PASSWORD: "password"
    volumes:
      - local_pgdata:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: jgeschwa@test.com
      PGADMIN_DEFAULT_PASSWORD: password
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  local_pgdata:
  pgadmin-data: